me: Deploy Storybook to storybook.panelist.dev

on:
  push:
    branches: [main]  # Triggers on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: storybook
          publish_dir: ./storybook-static
          cname: storybook.panelist.dev
